# Generated by Django 6.0.6 on 2026-07-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_seeking', models.BooleanField(default=False)),
                ('initial_wealth', models.DecimalField(decimal_places=2, default=100000, max_digits=10)),
                ('annual_return', models.DecimalField(decimal_places=2, default=6, max_digits=5)),
                ('return_std', models.DecimalField(decimal_places=2, default=12, max_digits=5)),
                ('annual_withdrawal', models.DecimalField(decimal_places=2, default=10000, max_digits=10)),
                ('inflation_rate', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('inflation_std', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('years', models.IntegerField(default=30)),
                ('runs', models.IntegerField(default=100)),
                ('target_success_rate', models.DecimalField(decimal_places=2, default=80, max_digits=5)),
            ],
        ),
    ]
