# Generated by Django 6.0.6 on 2026-07-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_seeking', models.BooleanField(default=False)),
                ('initial_wealth', models.FloatField(default=100000)),
                ('annual_return', models.FloatField(default=6)),
                ('return_std', models.FloatField(default=12)),
                ('annual_withdrawal', models.FloatField(default=10000)),
                ('inflation_rate', models.FloatField(default=2.5)),
                ('inflation_std', models.FloatField(default=2.5)),
                ('years', models.IntegerField(default=30)),
                ('runs', models.IntegerField(default=100)),
                ('target_success_rate', models.FloatField(default=80)),
            ],
        ),
    ]
